version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit:2.15.6-ubuntu16
    ports:
      - "29418:29418"
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - ldap
      - postgres
    volumes:
      - gerrit-etc-volume:/var/gerrit/etc
      - gerrit-git-volume:/var/gerrit/git
      - gerrit-index-volume:/var/gerrit/index
      - gerrit-cache-volume:/var/gerrit/cache
      - gerrit-db-volume:/var/gerrit/db
#init    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit
    environment:
      - CANONICAL_WEB_URL=http://127.0.0.1:8080

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=gerrit20181019
      - POSTGRES_DB=reviewdb

  ldap:
    image: osixia/openldap:1.2.2
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION="Bankledger Inc."
#      - LDAP_DOMAIN="bankledger.com"
#      - LDAP_BASE_DN="dc=bankledger,dc=com"
      - LDAP_ADMIN_PASSWORD=gerrit20181019
    volumes:
      - ldap-volumes:/var/lib/ldap
      - slapd-volumes:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - "6443:443"
#      - "6080:80"
    links:
      - ldap
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
#    volumes:
#      - ./support-files--phpldapadmin/login-dn-env.yaml:/container/environment/01-custom/env.yaml

volumes:
  gerrit-etc-volume:
  gerrit-git-volume:
  gerrit-index-volume:
  gerrit-cache-volume:
  gerrit-db-volume:
  postgres-data-volume:
  ldap-volumes:
  slapd-volumes:
